### ISSUE TITLE
大佬好---Kafka社區關注者

### ISSUE THREAD

**Issue by xijiu** [m1a2st/mini-spring#1]
大佬好，我注意到你經常活躍在Kafka社區，對Kafka有獨到的認識與見解。
我對Kafka也很感興趣，所以想要大佬一個聯繫方式（主頁上沒找到），方便後續溝通交流。

只能通過這種方式留言哈。盼回復

**Comment by m1a2st** [comment]
你好，不知道你有沒有辦法使用 slack，因為我們都常都在那上面討論，這樣會比較方便

**Comment by xijiu** [comment]
嗯，可以的，我剛已經下載好了，具體怎麼加入呢？

**Comment by m1a2st** [comment]
會有一個大廳的頻道，你可以稍微自我介紹後，說自己想要做 Kafka 然後加入 Kafka 的頻道就可以了，也有其他專案可以看看
